# Generated by Django 4.2.1 on 2023-05-26 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customers',
            name='age',
        ),
    ]
